name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [self-hosted, linux]   # runs directly on your VM
    steps:
      - uses: actions/checkout@v4

      - name: Ensure Docker/Compose available
        run: |
          set -e
          if command -v docker >/dev/null 2>&1; then
            echo "Docker OK: $(docker --version)"
          else
            echo "Docker not installed on VM"; exit 1
          fi

          # Compose v2 plugin check
          if docker compose version >/dev/null 2>&1; then
            docker compose version
          else
            echo "Docker Compose v2 plugin missing on VM"; exit 1
          fi

      - name: Create external network (if needed)
        shell: bash
        run: |
          set -euo pipefail
          if ! docker network inspect labo03-network >/dev/null 2>&1; then
            docker network create labo03-network
            echo "Created docker network: labo03-network"
          else
            echo "Docker network already exists: labo03-network"
          fi

      - name: Create .env if missing (printf)
        shell: bash
        run: |
          set -euo pipefail
          if [[ ! -f .env ]]; then
            printf "%s\n" \
            "DB_HOST=mysql" \
            "DB_PORT=3306" \
            "DB_NAME=labo03_db" \
            "DB_USER=labo03" \
            "DB_PASS=labo03" \
            "REDIS_HOST=redis" \
            "REDIS_PORT=6379" \
            "REDIS_DB=0" \
            > .env
          fi

      - name: Build & up
        run: |
          docker compose pull || true
          docker compose build
          docker compose up -d
          docker image prune -f || true